### ISSUE TITLE
An error occurred updating the stats database table, please try again or contact support.

### ISSUE THREAD

**Issue by faaezahmd** [TheCraigHewitt/Seriously-Simple-Stats#38]
I am seeing an alert that says "**Seriously Simple Stats needs to perform an update to the stats database table. Click below to perform this one-time update.**".

When I click on update I an error message "**An error occurred updating the stats database table, please try again or contact support.**".

Can someone explain, what's causing the error?

Plugin Version: 1.19.12
Wordpress Version: 4.9.8

**Comment by jonathanbossenger** [comment]
@faaezahmd are you able to check if the _ssp_stats table exists? We've had one or two instances where the stats table doesn't get created in the WordPress database.
