### ISSUE TITLE
New listening sources - Spotify

### ISSUE THREAD

**Issue by Rokeer** [TheCraigHewitt/Seriously-Simple-Stats#66]
Thanks for the great plugin!

Currently, Spotify draws more and more podcast listeners. It will be great if you could integrate Spotify stat as well.

Thank you so much.

**Comment by Rokeer** [comment]
Just try to do some quick research. It seems like that Spotify uses CDN to cache the podcast file. If I am correct, it will be hard to add stats for Spotify.

**Comment by jonathanbossenger** [comment]
@Rokeer thanks for the update. The other thing to consider is that Spotify specifically don't have a public API for any non-integration partners, so it would mean that each user would need access to the Spotify API, to be able to pipe their stats into the plugin.

It is for this reason that we offer a Spotify integration on our paid podcast hosting plans at Castos (https://castos.com/pricing/), which would allow you to gain access to Spotify stats for your show.

**Comment by Rokeer** [comment]
Cool Thanks!
